server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: AAVN@hv8499
    url: jdbc:mysql://localhost:3306/loginuser
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: nacu22984@gmail.com
    password: tumotdenchin19

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 25000
          writetimeout: 5000